<a href="https://colab.research.google.com/github/mupungijose-hue/Data-Analysis-Projects/blob/main/01Array_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Array Basics**

In [ ]:
import numpy as np
array = np.array(range(5))
array

array([0, 1, 2, 3, 4])

In [ ]:
array_2d = np.array([range(5), range(5)])
array_2d

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [ ]:
array.shape

(5,)

In [ ]:
array_2d.shape

(2, 5)

In [ ]:
array_2d.size
array_2d.ndim

2

In [ ]:
array_2d.T.shape

(5, 2)

In [ ]:
array_2d.T.shape

(5, 2)

In [ ]:
array.dtype

dtype('int64')

In [ ]:
np.array(['I', 'Love', 'Python'])

array(['I', 'Love', 'Python'], dtype='<U6')

**Array Creation**

In [ ]:
import numpy as np
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones(2, dtype= 'int')

array([1, 1])

In [ ]:
np.zeros(100, 'int').reshape(5, 20)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.identity(10).T

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [ ]:
np.linspace(0, 100, 11)
# multiples of 10 from zero to 100

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
np.linspace(0, 64, 9)

array([ 0.,  8., 16., 24., 32., 40., 48., 56., 64.])

**Random Number Generation**

In [ ]:
import numpy as np
rng = np.random.default_rng(616)
rng.random(10)

array([0.39682145, 0.86568572, 0.46040359, 0.30599848, 0.57381588,
       0.08888468, 0.88194347, 0.73228387, 0.73215182, 0.56233394])

In [ ]:
rng.normal(50, 5, 10)

array([53.2639188 , 46.02435073, 39.46788299, 42.75191377, 52.54802403,
       57.86374339, 47.26107561, 48.54153216, 53.60574701, 49.20798481])

**Indexing & Slicing Arrays**

In [ ]:
import numpy as np
integer_array = np.arange(12)
integer_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# note integer = index
integer_array[2]

np.int64(2)

In [ ]:
integer_array[-1]

np.int64(11)

In [ ]:
integer_array[3]

np.int64(3)

In [ ]:
integer_array[:5]

array([0, 1, 2, 3, 4])

In [ ]:
integer_array[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
integer_array[::2]

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
new_array = integer_array.reshape(3, 4)
new_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
new_array[2, 1]

np.int64(9)

In [ ]:
new_array[1:,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
new_array[:,3]

array([ 3,  7, 11])

**Array Operations**

In [ ]:
import numpy as np
rng = np.random.default_rng(616)
inventory = rng.integers(0, 100, 10)
inventory

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57])

In [ ]:
inventory - 24

array([ 15,  15,  69,  62,  24,  22,  24,   6, -13,  33])

In [ ]:
(inventory / 2).dtype

dtype('float64')

In [ ]:
price = (rng.random(10) * 10).round(2)
price


array([0.89, 8.82, 7.32, 7.32, 5.62, 3.4 , 0.63, 3.57, 2.03, 4.31])

In [ ]:
(price + inventory).sum()

np.float64(540.9100000000001)

In [ ]:
inventory_list = list(inventory)
inventory_list

[np.int64(39),
 np.int64(39),
 np.int64(93),
 np.int64(86),
 np.int64(48),
 np.int64(46),
 np.int64(48),
 np.int64(30),
 np.int64(11),
 np.int64(57)]

In [ ]:
[x + 2 for x in inventory_list]

[np.int64(41),
 np.int64(41),
 np.int64(95),
 np.int64(88),
 np.int64(50),
 np.int64(48),
 np.int64(50),
 np.int64(32),
 np.int64(13),
 np.int64(59)]

In [ ]:
[x * y for x,y in zip(inventory_list,price)]

[np.float64(34.71),
 np.float64(343.98),
 np.float64(680.76),
 np.float64(629.52),
 np.float64(269.76),
 np.float64(156.4),
 np.float64(30.240000000000002),
 np.float64(107.1),
 np.float64(22.33),
 np.float64(245.67)]

**Filtering Arrays**

In [ ]:
import numpy as np
my_array = np.arange(20)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
my_array % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [ ]:
my_array[my_array % 2 ==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
even_odd = np.array(['even', 'odd']*10)
even_odd

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [ ]:
even_odd != 'odd'

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [ ]:
even_odd[even_odd != 'odd']

array(['even', 'even', 'even', 'even', 'even', 'even', 'even', 'even',
       'even', 'even'], dtype='<U4')

In [ ]:
my_array[even_odd != 'odd'] = 0
my_array

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

In [ ]:
mask = (even_odd != 'odd') | (even_odd != 'even')
even_odd[mask]

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [ ]:
mask = (even_odd != 'odd') & (even_odd != 'even')
even_odd[mask]

array([], dtype='<U4')

**The Where Function**

In [ ]:
my_array

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

In [ ]:
np.where(my_array % 2 ==0, 'even', 'odd')

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [ ]:
np.where(my_array % 2 ==0, 'even', np.where(my_array == 9, my_array, 'odd'))

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       '9', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U21')

**Array Aggregation Methods**

In [ ]:
import numpy as np
rng = np.random.default_rng(616)
price = (rng.random(10) * 10).round(2)
price

array([3.97, 8.66, 4.6 , 3.06, 5.74, 0.89, 8.82, 7.32, 7.32, 5.62])

In [ ]:
inventory = rng.integers(0, 100, 10)
inventory

array([80, 33, 60,  6, 31, 35, 16, 20, 29, 43])

In [ ]:
price.mean()

np.float64(5.6)

In [ ]:
inventory.mean()

np.float64(35.3)

In [ ]:
inventory.min()

np.int64(6)

In [ ]:
inventory.std()

np.float64(20.48438429633656)

In [ ]:
(price * inventory)

array([317.6 , 285.78, 276.  ,  18.36, 177.94,  31.15, 141.12, 146.4 ,
       212.28, 241.66])

In [ ]:
(price * inventory).sum()

np.float64(1848.2900000000002)

In [ ]:
price_2d = price.reshape(5, 2)
price_2d

array([[3.97, 8.66],
       [4.6 , 3.06],
       [5.74, 0.89],
       [8.82, 7.32],
       [7.32, 5.62]])

In [ ]:
#sum of individual columns
price_2d.sum(axis = 0)

array([30.45, 25.55])

In [ ]:
# sum of rows
price_2d.sum(axis = 1)

array([12.63,  7.66,  6.63, 16.14, 12.94])

In [ ]:
price_2d.mean(axis = 0)

array([6.09, 5.11])

**Array Functions**

In [ ]:
import numpy as np
price = np.array([2.6 , 7.2, 6.92, 3.88, 0.78, 2.67, 8.87, 0.23, 5.23, 6.3])
inventory = np.array([79, 22, 20, 48, 8, 76, 12, 16, 5, 64])
product_value = price * inventory
product_value

array([205.4 , 158.4 , 138.4 , 186.24,   6.24, 202.92, 106.44,   3.68,
        26.15, 403.2 ])

In [ ]:
product_value.sort()
product_value

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])

In [ ]:
reshaped_product_value = product_value.reshape(2, 5)
reshaped_product_value

array([[  3.68,   6.24,  26.15, 106.44, 138.4 ],
       [158.4 , 186.24, 202.92, 205.4 , 403.2 ]])

In [ ]:
np.median(reshaped_product_value)

np.float64(148.4)

In [ ]:
np.percentile(reshaped_product_value, 50)

np.float64(148.4)

In [ ]:
np.percentile(reshaped_product_value, 100)

np.float64(403.2)

In [ ]:
np.percentile(reshaped_product_value, 0)

np.float64(3.68)

In [ ]:
np.sqrt(reshaped_product_value)

array([[ 1.91833261,  2.4979992 ,  5.11370707, 10.3169763 , 11.76435294],
       [12.58570618, 13.64697769, 14.24499912, 14.33178286, 20.07984064]])

In [ ]:
np.unique(reshaped_product_value)

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])

**Sorting Arrays**

In [ ]:
import numpy as np
product_value = np.array([205.4, 158.4, 138.4, 186.24, 6.24, 202.92, 106.44, 3.68, 26.15, 403.2])
product_value

array([205.4 , 158.4 , 138.4 , 186.24,   6.24, 202.92, 106.44,   3.68,
        26.15, 403.2 ])

In [ ]:
np.sort(product_value)

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])

In [ ]:
product_value

array([205.4 , 158.4 , 138.4 , 186.24,   6.24, 202.92, 106.44,   3.68,
        26.15, 403.2 ])

In [ ]:
product_value.sort()

In [ ]:
#minimum value
product_value[0]

np.float64(3.68)

In [ ]:
#maximum value
product_value[-1]

np.float64(403.2)

In [ ]:
#reverse
product_value[::-1]

array([403.2 , 205.4 , 202.92, 186.24, 158.4 , 138.4 , 106.44,  26.15,
         6.24,   3.68])

**`Vectorization & Broadcasting**